### ISSUE TITLE
Automated Price Reserve Setup Fail

### ISSUE THREAD

**Issue by tphanson** [KyberNetwork/smart-contracts#388]
I met this kind of error when try to configuring Automated Price Reserve.
* Command:

```
node liquidityReserveDeployer.js --config-path ropsten.json --gas-price-gwei 30 --rpc-url https://ropsten.infura.io --print-private-key true --network-address "0x3f9a8e219ab1ad42f96b22c294e564b2b48fe636"
```

* Error details:

```
Error: Error: [number-to-bn] while converting number undefined to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "undefined"
    at Object.toBN (/Users/admin/Desktop/kyber-smart-contracts/node_modules/web3-utils/src/utils.js:64:15)
    at /Users/admin/Desktop/kyber-smart-contracts/web3deployment/liquidityReserveDeployer.js:159:46
    at Array.forEach (<anonymous>)
    at parseInput (/Users/admin/Desktop/kyber-smart-contracts/web3deployment/liquidityReserveDeployer.js:148:28)
    at Object.<anonymous> (/Users/admin/Desktop/kyber-smart-contracts/web3deployment/liquidityReserveDeployer.js:303:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

I invested a bit of my time and recognized that in [the guide](https://developer.kyber.network/docs/AutomatedReservesGuide/) you told that `The most important properties are symbol, name, decimals, and address. The rest can be ignored. So you can specify your token details, filling in these fields.` and indeed, you ignored them in ETH config.

```
"ETH": {
      "name": "Ethereum",
      "decimals": 18,
      "address": "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
    }
```

However, when I come to `liquidityReserveDeployer.js` I saw,

```
const dict = {
        minimalRecordResolution : web3.utils.toBN(val["minimalRecordResolution"]),
        maxPerBlockImbalance : web3.utils.toBN(val["maxPerBlockImbalance"]),
        maxTotalImbalance : web3.utils.toBN(val["maxTotalImbalance"])
      };
```
So, obviously `val["minimalRecordResolution"` might be undefined in ETH and then led to the error.
What do you think? Please let me know If I missed something. In case I was right, please edit either your guide or your code to make them fit each others. Thanks for reading.

**Comment by tphanson** [comment]
I got around by

```
const dict = {
      minimalRecordResolution: web3.utils.toBN(val["minimalRecordResolution"] ? val["minimalRecordResolution"] : 0),
      maxPerBlockImbalance: web3.utils.toBN(val["maxPerBlockImbalance"] ? val["maxPerBlockImbalance"] : 0),
      maxTotalImbalance: web3.utils.toBN(val["maxTotalImbalance"] ? val["maxTotalImbalance"] : 0)
    };
```
But it brought me to another error

```
deploying conversion rates
TypeError: Cannot read property 'bytecode' of undefined
    at deployContract (/Users/admin/Desktop/kyber-smart-contracts/web3deployment/liquidityReserveDeployer.js:82:53)
    at main (/Users/admin/Desktop/kyber-smart-contracts/web3deployment/liquidityReserveDeployer.js:222:61)
    at process._tickCallback (internal/process/next_tick.js:68:7) Promise {
  <rejected> TypeError: Cannot read property 'bytecode' of undefined
      at deployContract (/Users/admin/Desktop/kyber-smart-contracts/web3deployment/liquidityReserveDeployer.js:82:53)
      at main (/Users/admin/Desktop/kyber-smart-contracts/web3deployment/liquidityReserveDeployer.js:222:61)
      at process._tickCallback (internal/process/next_tick.js:68:7) }
```

This is my [ropsten.json](https://trello-attachments.s3.amazonaws.com/5bdfb1ca38c3d5366cdfe564/5c474199f09703442f67093a/205ba18595b930704958293df9a50651/ropsten.json)

**Comment by ilanDoron** [comment]
can u try again now.

we fixed some conflicting web3 packages issue.

**Comment by tphanson** [comment]
thanks @ilanDoron , I got around by ayobuenavista's patch.
